#!/bin/bash

# Use ⁄ ("fraction slash") for replacing slashes in file names.
readonly SLASH_REPLACER='⁄'

# It's okay to hardcode `-l 8` here as a sensible default without checking
# whether `-l` is also in "$@", because the way that dmenu works allows a later
# argument to override an earlier one. That is, if the user passes in `-l`, our
# one will be ignored.
CACHE_DIR="/tmp/clipmenu.$USER"
chosen_file=$(cd $CACHE_DIR && find * | sed "s#$SLASH_REPLACER#/#g" | dmenu -l 8 "$@")

[[ $chosen_file ]] || exit 1

for selection in clipboard primary; do
    if type -p xsel &>/dev/null; then
        xsel -i --"$selection" < "$CACHE_DIR/$chosen_file"
    else
        xclip -sel "$selection" < "$CACHE_DIR/$chosen_file"
    fi
done
